title: DigiKAR Ontology Design Patterns
description: Dokumentation der Ontologie-Entwurfsmuster aus dem DigiKAR-Projekt, veröffentlicht am 22.03.2023.
theme: minima

header_pages:
  - index.md
  - intro.md
  - odp.md
  - kos.md
  - impr.md


social_links:
  twitter: digi_KAR
  
