title: DigiKAR Ontology Design Patterns
description: Dokumentation der Ontologie-Entwurfsmuster aus dem DigiKAR-Projekt
theme: minima

header_pages:
  - index.md
  - intro.md
  - odp.md
  - kos.md

  
